name: TV Card Gui
description: 📺 TV Remote Card
type: lovelace
keywords:
  - tvcard
  - remote
  - tv
  - television
author:
  name: mar_robHD/Gui
license: Apache License, Version 2.0
files:
  - tv-card-gui.js
  - tv-card-editor-gui.js
